### ISSUE TITLE
[ 0.5pt ] Set Up Project

### ISSUE THREAD

**Issue by Oklukeok** [J2ZROMERO/RecipeApp#3]

**Comment by Oklukeok** [comment]
### **_Set Up the project_**
- Create RoR project
-  Install all needed gems
- Link the project to Postgres database
- Install Capybara
- Install Devise
- Update the Readme File

**Comment by J2ZROMERO** [comment]
Hi @Oklukeok and @J2ZROMERO ,


Highlights 🚀

✔️ The project was set up correctly.
✔️ All the mentioned points were added.
